name: e_state_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-266.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  rxdart: ^0.28.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  firebase_app_check: ^0.3.0+4
  image_picker: ^1.1.2
  intl_phone_number_input: ^0.7.0+2
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0

  #google map
  google_maps_flutter: ^2.9.0
  
  #firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  firebase_messaging: ^15.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/png/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

