class AppAssets {
  AppAssets._();

  static const vectors = 'assets/vectors';

  static const vector = '$vectors/vector.svg';
  static const pattern = '$vectors/pattern.svg';
  static const google = '$vectors/google.svg';
  static const facebook = '$vectors/facebook.svg';
  static const search = '$vectors/search.svg';
  static const searchC = '$vectors/searchC.svg';
  static const filter = '$vectors/filter.svg';
  static const apartment1 = 'assets/png/a1.png';
  static const apartment2 = 'assets/png/a2.png';
  static const profilJames = "$vectors/profil_james.svg";
  static const all = "$vectors/all.svg";
  static const land = "$vectors/land.svg";
  static const house = "$vectors/house.svg";
  static const building = "$vectors/building.svg";
  static const rectangle = "$vectors/rectangle.svg";
  static const franciscoApartment = "$vectors/francisco_apartment.svg";
  static const home = '$vectors/home.svg';
  static const homeActive = 'assets/vectors/homeActive.svg';
  static const searchActive = '$vectors/searchActive.svg';
  static const saveActive = '$vectors/saveActive.svg';
  static const messageActive = '$vectors/messageActive.svg';
  static const settingsActive = '$vectors/settingsActive.svg';
  static const searchb = '$vectors/searchB.svg';
  static const message = '$vectors/message.svg';
  static const save = '$vectors/save.svg';
  static const polygon = '$vectors/polygon.svg';
  static const settings = '$vectors/settings.svg';
  static const edit = '$vectors/edit.svg';
  static const bathroom = '$vectors/bathroom.svg';
  static const bedroom = '$vectors/bedroom.svg';
  static const kitchen = '$vectors/kitchen.svg';
  static const background = 'assets/png/background.png';
  static const call = '$vectors/call.svg';
  static const callB = '$vectors/callB.svg';
  static const back = '$vectors/back_btn.svg';
  static const avatar = 'assets/png/profile.png';
  static const add = '$vectors/add.svg';
  static const person = "$vectors/person.svg";
  static const lock = "$vectors/lock.svg";
  static const privacy = "$vectors/privacy.svg";
  static const data = "$vectors/data.svg";
  static const star = "$vectors/star.svg";
  static const schedule = "$vectors/schedule.svg";
  static const terms = "$vectors/terms.svg";
  static const phone = "$vectors/phone.svg";
  static const logout = "$vectors/logout.svg";
  static const messageB = "$vectors/messageB.svg";
  static const offer = '$vectors/offer.svg';
  static const company = '$vectors/company.svg';
  static const list = "$vectors/list.svg";
}
